// cars.js – полный список автомобилей (замените на ваши данные, здесь сокращён для примера)
window.carsData = {
    "E": [
        "chevrolet bel air coupe 26s",
        "Dodge chalenger r/t 383 magnum",
        "Dodge chalenge   r/t 69",
        "Fiat Grande Punto",
        "Ford Crown victoria police intercep",
        "Ford Escort MK1  RS 1600",
        "Fort Lotus Cortina",
        "Fort model 18",
        "Hammer H1 Alpha",
        "mazda mx-5",
        "nissan 240sx",
        "Pontiac Firebird Formula",
        "Pontiac gto 65",
        "porshe 914-6 gt",
        "scion tC",
        "Snart Fortwd (w451)",
        "toyota corolla gt-s (AE 86)",
        "volkswagen beetle 1200 (type 1)",
        "volkswagen golf gt1 (MK1)",
        "volkswagen type2 (t1)",
        "Volvo 242 OL"
    ],
    "D": [
        "Acura Rsx  TYPE-S (OCS)",
        "Alfa romeo Breda",
        "Audi A3 3.2 quattro",
        "audi quatro 20v",
        "audi tt 3.2 quattro (bn)",
        "BMW 135i coupe (e82)",
        "BMW Z4 M Coupe (e85)",
        "Buick gnx",
        "Cadilac escalade (gmt900)",
        "chevrolet camaro ss 395 67",
        "chevrolet cvegelle ss 454",
        "chevrolet cobalt ss 08",
        "cheevrollete carvette stingray (c2)",
        "chevrolet camino ss",
        "dodge challenger r/t 383 magnum",
        "dodge charger r/t 69",
        "ford escort mk1 RS 1600",
        "Ford escort rs cosworth",
        "Ford fiesta st (gen 6)",
        "ford lotus cortina",
        "ford mustang boss 302 (gen 1)",
        "Ford mustang coupe (gen 1)",
        "ford mustang gt (gen3)",
        "ford police interceptor utility",
        "honda civic type-r (ek9)",
        "gonda integra type r (DC2)",
        "hammer hi alfa",
        "hyudai tiburdon gt (gk)",
        "Lancia 037 stradale",
        "Lacia Delta hf integrale evoluzione II",
        "land rover evoque coupe",
        "lexus ls300",
        "lexus ls350",
        "mazda  mazdaspeed3 (8k)",
        "mazda mx-s(na)",
        "mazda ms-s(nc)",
        "mazda rx-7(fc35)",
        "mazda rx-8 (se3p)",
        "mercedes-benz 190e 2.5-16 evolution II",
        "mercedes-benz300 sl  (w198)",
        "mercedes-benz sls500 (rs230)",
        "mitsubishi eclipse gs-t",
        "mitsubishi eclipse gt(dk4a)",
        "mitsubishi fto gp version R",
        "nissan 200sx turbo(s14)",
        "nissan 240 sx se (se13)",
        "nissan  300zx (z32)",
        "nissan firelady 240zg",
        "skyline  2000gt-r(c10)",
        "peuget 206 gti (t1)",
        "plymaotch hemi Cuda",
        "plymaotc road runner",
        "pontiac gto 65",
        "pontiac soltice gxp",
        "porshe 914-6 gt",
        "renaut sport clio v6",
        "renaut sport megane coupe Tce 180",
        "Scion Tc",
        "subaru brz",
        "toyota celica gt-four (st205)",
        "toyota celica gt-s(t230)",
        "toyota corolla gt-s(ae86)",
        "volkswagen beetle 1200 (type1)",
        "volkswagen golf  gt1 (mk1)",
        "volkswagen golf gt1 (mk4)",
        "volkswagen  golf r32 (mk5)",
        "volkswagen scirroco 2.0 tsi",
        "volvo 242 ol"
    ],
    "C": [
        "Acura RSX TYPE-s (DCS)",
        "ALFA Romeo 4C",
        "AUDI RS 3 Sportback",
        "AUDI RS4 (B7)",
        "AUDI SS(B8)",
        "AUDI TT COUPE (8J)",
        "BMW 135i coupe(e82)",
        "BMW 3.0 CSL GR.S (E9)",
        "BMW m3 (E46)",
        "BMW M3 competition touning xdrive",
        "BMW m3 sport evolution (E30)",
        "BMW m5 (e39)",
        "BMW m6 Convertible(e64)",
        "BMW z4 m Coupe (e85)",
        "BMW z4 sDrive35is (e89)",
        "buick gnx",
        "Cadillac escalade (gmt900)",
        "chevrolet camaro ss 396 67",
        "chevrolet ss 454",
        "chevrolet  corvette (cs)",
        "stingray (c2)",
        "camino ss",
        "chrysler hemi 3000 srt-8",
        "dmc delorean (s3)",
        "doodge chalenger concept",
        "doodge charger srt8 (ld)",
        "doodge srt8 super bee(lx)",
        "ferrari testarossa (f110)",
        "ford capri rs 3100 gr4",
        "ford -150 svt raptor gen12",
        "ford focus rs gen 2",
        "ford mustang boss 302 gen 1",
        "ford mustang gt gen 3",
        "ford mustang gt (gen5)",
        "ford mustang svt cobra r gen 4",
        "ford terlingua mustang  gen5",
        "honda civic type R (ek9)",
        "honda integra type-r DC 2",
        "honda nsx r",
        "honds s2000 ap2",
        "infiniti g35 coupe v35",
        "jaguar e-type lightweight",
        "jaguar xkr",
        "lomborgini countach 5000 quattrovalvole",
        "lomborgini miura sv",
        "lancia 037 stradale",
        "lacia delta hf integrale evoluzione II",
        "land rover range rover sport svr (L494)",
        "lexus is300",
        "lotus elise 111r",
        "lotus exige cup 260",
        "marussia b1",
        "mazda rx-7 (FC35)",
        "mazda rx-7(FD35)",
        "mazda rx-7 type rz(FD35)",
        "Mazda rx-8(r3)",
        "mazda rx-8(se3p)",
        "mercedes-benz 300 sl (w198)",
        "mercedes-benz clk 500(c209)",
        "mitsubishi 3000gt vr-4 (z15am)",
        "mitsubushi eclipse gs-t",
        "mitsubishi eclipse gt (dk4a)",
        "mitsubishi fto gp version r",
        "mitsubishi lancer evolution IX MR-edition",
        "mitsubishi evolution VI gsr",
        "mitsubishi lancer evolution VIII",
        "mitsubishi lancer evolution x",
        "nissan 200sx turbo (s14)",
        "nissan 240sx se (s13)",
        "nissan 300zx (z32)",
        "nissan 350z (z33)",
        "nissan 370z (z34)",
        "nissan 370z roadster touring (z34)",
        "nissan silvia (s15)",
        "nissan skyline 2000gt-r(c10)",
        "nissan skyline gt-r (r32)",
        "skyline gt-r v-spec (r33)",
        "skyline gt-r v-spec (r34)",
        "porsche boxster spyder (987)",
        "porsche cayenne turbo s (957)",
        "porsche cayman s",
        "Renault sport magane r s 250",
        "scion tC",
        "Shelby gt500 67",
        "Subaru impreza wrx sti (gob-f)",
        "Subaru impreza wrx sti gr",
        "Subaru  wrx type r sti (gc8-f)",
        "toyota corolla gt-s(ae86)",
        "toyota mr2 turbo rev 3",
        "toyota supra rz (mk4)",
        "volkswagen golf gti mk4",
        "volkswagen golf r32 mk5",
        "scirocco 2.0 tsi"
    ],
    "B": [
        "Acura RSX Type-s DCS",
        "ALFA ROMEO 4c",
        "alfa romeo 8C competizione",
        "alfa romeo giulia quadrifoglio",
        "aston martin DB9",
        "aston martin v12 vantage",
        "audi a1 clubsport quattro",
        "audi quattro 20v",
        "audi R8 coupe 4.2 fsp quattro",
        "audi r8 coupe 5.2 FSI quattro",
        "audi rs 3 sportback",
        "audi tt rs coupe 8j",
        "bently continental supersports",
        "bmw 1 series m coupe E82",
        "BMW 3.0 csl hommage r",
        "BMW m3 (e46)",
        "BMW m3 (e92)",
        "BMW m3 gtr e46",
        "BMW m3 sport evolution e30",
        "bmw m5 e39",
        "BMW m5 f90",
        "BMW m6 convertible e46",
        "bmw m6 coupe e63",
        "cadillac cts-v gen 2",
        "caterham superlight r500",
        "chevrolet chevelle ss454",
        "chevrolet corvette stingray c2",
        "chevrolet corvette stingray c7",
        "chevrolet corvette stingray c8",
        "chevrolet camino ss",
        "chrysler hemi 300c srt-8",
        "doodge chalenger concept",
        "doodge carger srt8(LD)",
        "doodge srt8 super bee lx",
        "ferrari 360 spider",
        "ferrari f40",
        "ferrari f50",
        "ferrari testarossa f110",
        "ford escort rs cosworth",
        "ford-150 svt raptor gen12",
        "fort focus rs gen2",
        "fort gt40",
        "fort mustang boss 302 gen1",
        "mustang boss 302 gen 2",
        "mustang gt gen 5",
        "mustang svt cobra r gen 4",
        "terlingua mustang gen5",
        "honda nsx type r",
        "honda s2000 ap2",
        "hyudai tiburon gt",
        "jaguar e-type lightweight",
        "jaguar f-type r x152",
        "jaguar xe sv project 8 (x760)",
        "jaguar xkr",
        "jeep grand cherokee srt 8 wk2",
        "lamborgini contach 5000 quatrovalvole",
        "lamborghini Diablo sv",
        "lamborghini murcirlago",
        "land rover range rover sport svr l494",
        "lexus IS-F",
        "lotus emira",
        "lotus esprit v8",
        "lotus europa s",
        "maserati grancabrio",
        "maserati granturismo s",
        "mazda rx-7 fd35",
        "mazda rx-8 r3",
        "mazda rx8 se3p",
        "mercedes-benz cls 53 amg c219",
        "mercedes-benz sls amg",
        "mitsubushi 3000gt vr-4 z15am",
        "mitsubushi eclipse gs-t",
        "mitsubushi gs-t elite",
        "mitsubushi gt dk4a",
        "mitsubushi lancer evolution IX MR-edition",
        "mitsubushi lancer evolution x",
        "nissan 200sx turbo s14",
        "nissan 350z z33",
        "nissan 370z z34",
        "nissan silvia s15",
        "nissan skyline gt-r nismo lm r33",
        "nissan skyline gt-r v-spec r33",
        "nissan skyline gt-r v-spec r34",
        "nissan z proto rz34",
        "polestar 1",
        "pontiac gto 05",
        "porsche 911 carrera rsr 3.0",
        "porsche 911 gt2 993",
        "porsche 911 turbo s 996",
        "porsche 959",
        "porsche cayman s",
        "porsche panamera turbo 970",
        "shelby cobra daytona coupe",
        "shelby cobra 427 s/c",
        "subaru brz",
        "impreza wrx sti gr",
        "subaru impreza wrx type r sti gc8-f",
        "tesla model s p900",
        "toyota mr2 turbo rev 3",
        "toyota supra rz mk4",
        "vauxhall monaro vxr",
        "volkswagen golf r32 mk5"
    ],
    "A": [
        "Alpha Romeo 8c compitizion",
        "Alpha Romeo Giullia quadrifoglio",
        "ariel atom 500 v8",
        "aston martin DB9",
        "aston martin DBR9 GT1",
        "aston martin  DBS v12",
        "aston martin DBS volante",
        "aston martin  v12 vantage",
        "audi a1 clubsport quattro",
        "audi r8 coupe 3.2 fsi quattro",
        "audi r8 coupe 5.2 fsi quattro",
        "audi r8 v10 perfomance",
        "audi s5 b8",
        "bentley continental supersport",
        "bentley continental supersport convertible",
        "Bmw 1 series coupe e82",
        "bmw 3.0 csl gr.5",
        "bmw 3.0 csl hommage r",
        "bmw m1 procar e26",
        "bmw m3 e92",
        "bmw m3 gtr e46",
        "bmw m3 gtr alms",
        "bmw m3 gts e92",
        "bmw m3 sport evolution e30",
        "bmw m4 f82",
        "bmw z4 m coupe e85",
        "cadillac cts-v gen2",
        "cadillac sixteen",
        "chevrolet camaro zl1 12",
        "chevrolet  stingray c8",
        "chevrolet  corvette c6",
        "chevrolet  corvette c6 carbom limited edition",
        "chevrolet  corvette zr1 c6",
        "chrysler hemi 300c srt-8",
        "doodge challenger concept",
        "doodge challenger srt hellcat",
        "doodge srt8 super bee lx",
        "doodge viper gtx vx 1",
        "doodge viper  srt-10 zb II",
        "doodge srt-10 acr ab II",
        "ferrari 599 gtb fiorand",
        "ferrari california",
        "ferrari enzo f140",
        "ferrari f50",
        "ford capri rs3100gr4",
        "ford f-150 svt raptor gen 12",
        "ford focus rs gen 2",
        "ford gt gen1",
        "ford gt gen 2",
        "ford mustang boss 302 gen 5",
        "ford mustang gt gen 6",
        "ford mustang rtr x",
        "ford police interceptor sedan (concept)",
        "Ford shelby gt500 super snake gen5",
        "Ford   shelby terlingua mustang gen 5",
        "hennessey camaro exorcist",
        "infinity g35 coupe v35",
        "jaguar c-x75",
        "jaguar xe sv project 8 x760",
        "jaguar  xj220",
        "jaguar xkr",
        "lamborghini aventador j",
        "lamborghini aventador lp 700-4",
        "lamborghini aventador lp 750-4 5v",
        "lamborghini esoque",
        "lamborghini gallardo",
        "lamborghini lp550-2 valentindo balboni",
        "lamborghini galardo lp 560-4",
        "lamborghini galardo lp 560-4 spyder",
        "lamborghini huracan lp 610-4",
        "lamborghini miura concept",
        "lamborghini murcielago lp 640",
        "lamborghini murcielago lp 640-4 roadster",
        "lamborghini murcielago lp670-4 5v",
        "lamborghini revention",
        "lamborghini fkp 37",
        "lexus IS-F",
        "lexus lfa",
        "lotus esprit v8",
        "lotus evora",
        "lotus exige cup 260",
        "marussia B2",
        "maserati granturismo mc stradale",
        "maserat mc 12 m1334",
        "mazda furai",
        "mazda rx-7 FD35",
        "mazda  rx-7 type RZ (FD35)",
        "Mclaren 12c 13",
        "Mclaren 570s",
        "Mclaren f1",
        "mercedes-benz c63 amg coupe black series",
        "mercedes-benz clk 500 c209",
        "mercedes-benz clk-gtr",
        "mercedes-benz sl65 amg black series r230",
        "mercedes-benz slr 722 edition",
        "mercedes-benz sls amg",
        "mitsubushi  lancer evolution VIII",
        "mitsubushilancer evolution x",
        "nfs battleefield heroes suv",
        "nissan 350z z33",
        "nissan 370z",
        "nissan gt-r r35",
        "nissan gt-r nismo gt1 r35",
        "nissan gt-r specV r35",
        "nissan silvia s15",
        "nissan skyline r32",
        "nissan gt-r nismo z-tune r34",
        "nissan syline gt-r v-spec r34",
        "nissan z proto rz34",
        "pagani zonfa f",
        "pagani zonfa f roadster",
        "polestar 1",
        "porsche 911 carrera rsr 3.0",
        "porsch 911 carrera s 911",
        "porsche 911 gt1-98 996",
        "porsche gt2 996",
        "porsche  911 gt2 997",
        "porsche gt3 rs 997.2",
        "porsche 911 turbo 997",
        "porsche 918 rsr",
        "porsche 959",
        "porsche carrera gt",
        "porsche cayman s",
        "renault sport megane r.s 250",
        "renaultsport r.s 01",
        "shelby cobra daytona coupe",
        "shelby cobra 427 s/c",
        "subaru impreza wrx sti gdb-f",
        "toyota supra rz mk4",
        "vauhall monaro vxr",
        "volkswagen w12 nardo"
    ],
    "S": [
        "aston martin one-77",
        "aston martin v12 vantage",
        "aston martin valkyrie",
        "aston martin vulcan",
        "audi r8 coupe 4.2 fsi quattro",
        "audi  r8 lms ultra",
        "bentley continental supersport",
        "BMW m1 procar e26",
        "BMW m3 gtr alms",
        "BMW m3 gts E92",
        "BMW m5 f90",
        "BMW z4 gt3 e89",
        "brabham BT62",
        "bugatti chiron",
        "bugatti LA Bolture noire",
        "Bugatti veyron 16.4",
        "buhatti veyron 16.4 super sport",
        "chevrolet camaro zl1 12 elite",
        "chevrolet  corvette z06 c6",
        "chevrolet  corvette z06 carbon limited edition c6",
        "chevrolet  corvette zr1 c6",
        "doodge challenger srt hellcat",
        "doodge viper gts vx I",
        "doodge viper  srt-10 acr zb II ELITE",
        "ferrari 488 pista",
        "ferrari 599 gtb fiorand",
        "ferrari 812 superfast",
        "ferrari enzo f140",
        "ferrari laferrari",
        "flanker F",
        "Ford capri rs 3100 gr.4",
        "ford gt gen 1",
        "ford gt gen 2",
        "mustang gt gen6",
        "ford gt 500 super snake gen 5",
        "gta spano gen1",
        "gumpert apollo s",
        "hennessey venom fs",
        "hennessey venom gt 12",
        "jaguar c-x75",
        "jaguar xj220",
        "koenigsegg agera",
        "koenigsegg ccx",
        "koenigsegg ccx ELITE",
        "koenigsegg ccxr edition",
        "koenigsegg one:1",
        "lamborghini aventador lp 700-4",
        "lamborgghini aventador lp 750-4 sv",
        "lamborgghini countach lpi 800-4",
        "lamborgghini gallardo 550-2 valentino valboni",
        "lamborgghini gallardo 560-4",
        "lamborgghini huracan lp 610-4",
        "lamborgghini murcielago lp 670-4 sv",
        "lamborgghini reventon",
        "lamborgghini sesto elemento",
        "lamborgghini veneno",
        "lexus lfa",
        "marussia B2",
        "maserati mc12 m1445",
        "mcklaren 12c 13",
        "mcklaren 12c 13 halloween edition",
        "mclaren f1",
        "mclaren p1",
        "mclaren speedtail",
        "mercedes-benz sl65 amg black series r230",
        "mercedes-benz slr mclaren stirling moss edition",
        "nissan gt-r specV r35",
        "nissan r390 gt1",
        "nissan skyline gt-r nismo z-tune",
        "pagani huayra",
        "pagani utopia",
        "pagani zonda cinque",
        "pagani zonda r",
        "porsche 911 carrera s 911",
        "porsche 911 gt2 rs weissach 991.2",
        "porsche 911 gt3 rs 4.0 997.2",
        "porsche 911 turbo 977",
        "porsche 918 spyder",
        "porsche carrera gt",
        "saleen r7 twin turbo"
    ]
};